import type { Config } from 'tailwindcss';

import baseConfig from '../../packages/ui/tailwind.config';

const config: Config & { safelist: string[] } = {
    content: [
        './app/**/*.{js,ts,jsx,tsx}',
        '../../packages/ui/src/**/*.{js,ts,jsx,tsx}',
    ],
    safelist: [
        'bg-primary-100',
        'bg-primary-200',
        'bg-secondary-100',
        'bg-secondary-200',
        'bg-secondary-300',
        'bg-tertiary-100',
        'bg-tertiary-200',
        'bg-tertiary-300',
        'bg-gray-100',
        'bg-gray-200',
        'bg-gray-300',
        'bg-gray-400',
        'bg-gray-500',
        'bg-gray-600',
        'bg-gray-700',
        'bg-gray-800',
        'bg-gray-900',
        'bg-point-green-100',
        'bg-point-green-200',
        'bg-point-blue-100',
        'bg-point-blue-200',
        'bg-point-yellow-100',
        'bg-point-yellow-200',
        'bg-error',
        'bg-error-100',
        'bg-error-200',
        'bg-black',
        'text-primary-100',
        'text-primary-200',
        'text-secondary-100',
        'text-secondary-200',
        'text-secondary-300',
        'text-tertiary-100',
        'text-tertiary-200',
        'text-tertiary-300',
        'text-gray-100',
        'text-gray-200',
        'text-gray-300',
        'text-gray-400',
        'text-gray-500',
        'text-gray-600',
        'text-gray-700',
        'text-gray-800',
        'text-gray-900',
        'text-point-green-100',
        'text-point-green-200',
        'text-point-blue-100',
        'text-point-blue-200',
        'text-point-yellow-100',
        'text-point-yellow-200',
        'text-error',
        'text-error-100',
        'text-error-200',
        'text-black',
    ],
    presets: [baseConfig],
};

export default config;
